/**
 * Reads results.csv and emits lib/run-data.ts at build time.
 *
 * The browser never parses CSV. This runs once, in Node, and writes a typed
 * module. Every metric is `number | null`; null means the turn produced no
 * measurement and must render as an em dash, never as zero.
 *
 * results.csv holds two appended runs of the harness (the writer opens in
 * append mode). Only the second run is published - see RUN_SLICE below.
 *
 * Usage: node scripts/generate-run-data.ts
 */

import { readFileSync, writeFileSync } from "node:fs";

const CSV_PATH = "results.csv";
const PROMPTS_PATH = "prompts.json";
const OUT_PATH = "lib/run-data.ts";

// results.csv contains run 1 (rows 0-47) then run 2 (rows 48-95). We publish
// run 2 only. Taking one run keeps `rep` a unique key within an arm+prompt,
// which is what audio_rep points at - across both runs it is not unique.
const RUN_SLICE = { start: 48, end: 96, label: "run 2 of 2 in results.csv" };

const ARMS = [
  { id: "mercury", name: "Mercury 2", csv: "inception-mercury-2" },
  { id: "haiku", name: "Haiku 4.5", csv: "anthropic-claude-haiku-4-5" },
] as const;

type ArmId = (typeof ARMS)[number]["id"];

/** RFC-4180 enough: handles quoted fields, embedded commas, and doubled quotes. */
function parseCsv(text: string): string[][] {
  const rows: string[][] = [];
  let row: string[] = [];
  let field = "";
  let quoted = false;
  for (let i = 0; i < text.length; i++) {
    const ch = text[i];
    if (quoted) {
      if (ch === '"') {
        if (text[i + 1] === '"') { field += '"'; i++; } else { quoted = false; }
      } else field += ch;
    } else if (ch === '"') quoted = true;
    else if (ch === ",") { row.push(field); field = ""; }
    else if (ch === "\n") { row.push(field); rows.push(row); row = []; field = ""; }
    else if (ch !== "\r") field += ch;
  }
  if (field.length || row.length) { row.push(field); rows.push(row); }
  return rows.filter((r) => r.some((c) => c.length));
}

/** Empty field means unmeasured. Returns null, never 0. */
function num(value: string | undefined): number | null {
  if (value === undefined || value.trim() === "") return null;
  const parsed = Number(value);
  return Number.isFinite(parsed) ? parsed : null;
}

function main() {
  const table = parseCsv(readFileSync(CSV_PATH, "utf8"));
  const header = table[0];
  const all = table.slice(1).map((cells) =>
    Object.fromEntries(header.map((h, i) => [h, cells[i] ?? ""])) as Record<string, string>
  );
  const rows = all.slice(RUN_SLICE.start, RUN_SLICE.end);

  const promptsFile = JSON.parse(readFileSync(PROMPTS_PATH, "utf8")) as {
    prompts: { id: string; prompt: string }[];
  };
  const promptText = new Map(promptsFile.prompts.map((p) => [p.id, p.prompt]));

  const csvToArm = new Map(ARMS.map((a) => [a.csv, a.id as ArmId]));

  const turns = rows.map((r) => ({
    arm: csvToArm.get(r.arm)!,
    promptId: r.prompt_id,
    rep: Number(r.rep),
    ttfa_s: num(r.ttfa_s),
    ttft_s: num(r.ttft_s),
    tts_handoff_s: num(r.tts_handoff_s),
    tts_ttfb_s: num(r.tts_ttfb_s),
    total_s: num(r.total_s),
    passed: r.passed === "True",
    error: r.error,
    answerText: r.answer_text,
  }));

  // Per prompt and arm, the published audio is the MEDIAN rep by ttfa_s - not
  // the fastest. audio_rep records which rep that is, so every clip on the page
  // maps to one measured row rather than to an average nobody can point at.
  const prompts = promptsFile.prompts.map((p) => {
    const results: Record<string, unknown> = {};
    for (const arm of ARMS) {
      const mine = turns
        .filter((t) => t.promptId === p.id && t.arm === arm.id && t.ttfa_s !== null)
        .sort((a, b) => (a.ttfa_s as number) - (b.ttfa_s as number));
      const median = mine.length ? mine[Math.floor((mine.length - 1) / 2)] : null;
      results[arm.id] = {
        ttfa_s: median ? median.ttfa_s : null,
        passed: median ? median.passed : null,
        audio_rep: median ? median.rep : null,
        answerText: median ? median.answerText : null,
      };
    }
    return { id: p.id, text: promptText.get(p.id) ?? p.id, results };
  });

  const meta = {
    prompts: promptsFile.prompts.length,
    reps: new Set(turns.map((t) => t.rep)).size,
    turns: turns.length,
    source: RUN_SLICE.label,
    csvUrl:
      "https://github.com/AnaMMedina21/medina-voice-benchmarking/blob/main/results.csv",
  };

  const banner = `// GENERATED by scripts/generate-run-data.ts from ${CSV_PATH}. Do not edit.
// Every metric is number | null. null means unmeasured: render an em dash,
// never zero. Published slice: ${RUN_SLICE.label}.\n`;

  const body =
    banner +
    `\nexport type ArmId = ${ARMS.map((a) => `"${a.id}"`).join(" | ")};\n` +
    `export type Metric = number | null;\n\n` +
    `export type Turn = {\n  arm: ArmId;\n  promptId: string;\n  rep: number;\n` +
    `  ttfa_s: Metric;\n  ttft_s: Metric;\n  tts_handoff_s: Metric;\n` +
    `  tts_ttfb_s: Metric;\n  total_s: Metric;\n  passed: boolean;\n` +
    `  error: string;\n  answerText: string;\n};\n\n` +
    `export type ArmResult = {\n  ttfa_s: Metric;\n  passed: boolean | null;\n` +
    `  audio_rep: number | null;\n  answerText: string | null;\n};\n\n` +
    `export type Prompt = {\n  id: string;\n  text: string;\n` +
    `  results: Record<ArmId, ArmResult>;\n};\n\n` +
    `export const ARMS = ${JSON.stringify(
      ARMS.map((a) => ({ id: a.id, name: a.name })), null, 2)} as const;\n\n` +
    `export const META = ${JSON.stringify(meta, null, 2)};\n\n` +
    `export const PROMPTS: Prompt[] = ${JSON.stringify(prompts, null, 2)};\n\n` +
    `export const TURNS: Turn[] = ${JSON.stringify(turns, null, 2)};\n`;

  writeFileSync(OUT_PATH, body);
  console.log(
    `wrote ${OUT_PATH}: ${turns.length} turns, ${prompts.length} prompts, ` +
    `${ARMS.length} arms (${RUN_SLICE.label})`
  );
}

main();
